services:

  backend:
    image: harshak07/devops-joke-backend:latest
    container_name: joke-backend

  frontend:
    image: harshak07/devops-joke-frontend:latest
    container_name: joke-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend